// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWG3cfWG8hKA5UxFynHDbi89ckNkKPXs',
    appId: '1:655240398483:web:2f6aa05ecc432385c6ef66',
    messagingSenderId: '655240398483',
    projectId: 'curious-bud',
    authDomain: 'curious-bud.firebaseapp.com',
    storageBucket: 'curious-bud.appspot.com',
    measurementId: 'G-9V5DPRTRTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_ks-vMjahy4yV4lFW_fgHSbxkuXKtV8',
    appId: '1:655240398483:android:9771bb38f26c1c0ac6ef66',
    messagingSenderId: '655240398483',
    projectId: 'curious-bud',
    storageBucket: 'curious-bud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9m_q6JTApZzfFUrzkWiZ29JuBjUUUrM',
    appId: '1:655240398483:ios:19b2aa76e855ac02c6ef66',
    messagingSenderId: '655240398483',
    projectId: 'curious-bud',
    storageBucket: 'curious-bud.appspot.com',
    iosClientId: '655240398483-b8ddb4o1mptmnhqiorc1126grokkqo3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.lablab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv9m_q6JTApZzfFUrzkWiZ29JuBjUUUrM',
    appId: '1:655240398483:ios:1d38ef8fc5c9dc9ac6ef66',
    messagingSenderId: '655240398483',
    projectId: 'curious-bud',
    storageBucket: 'curious-bud.appspot.com',
    iosClientId: '655240398483-71a6kup4gkk3h1tdb50k4h2tbpnd14a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lablab2.RunnerTests',
  );
}
